name: Generate Tarballs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
  - run: npm install
  - run: npm test

