name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm i

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # The default here is typically just `changeset version`, however a bug in npm workspaces
          # requires us to use an older version of npm for this particular update
          # ref: https://github.com/npm/cli/issues/3637
          version: "npx --yes npm@7.20.2 install && npx changeset version"
        env:
          GITHUB_TOKEN: ${{ secrets.GGITHUB_TOKEN }}
