name: Generate Tarballs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-tarballs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g npm@8 verdaccio
      - run: npm install
      - run: verdaccio
      - run: cat ~/.npmrc

