name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install -g npm@8
      - run: npm install
      - run: npm test