name: Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run monorepo-pack
      - run: pwd
      - run: ls -al
      - uses: actions/upload-artifact@v2
        with:
          name: tarballs
          path: ./*.tgz